// Build-time texture atlas packer.
//
// Walks `assets/`, decodes every image (png/webp), packs them into a single
// RGBA8 atlas via a simple skyline / shelf algorithm, and emits:
//   - $OUT_DIR/atlas.png        the packed atlas
//   - $OUT_DIR/atlas_data.rs    a Rust source file with sprite UV rects
//
// The .rs file is `include!`d from src/atlas.rs.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use image::{GenericImage, GenericImageView, ImageReader, RgbaImage};

const ATLAS_W: u32 = 2048;
const PADDING: u32 = 2;

fn main() {
    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let assets_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap()).join("assets");

    // Collect images (skip audio etc.)
    let mut entries: Vec<(String, RgbaImage)> = Vec::new();
    for entry in fs::read_dir(&assets_dir).expect("read assets/") {
        let entry = entry.unwrap();
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let ext = path
            .extension()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_lowercase();
        if !matches!(ext.as_str(), "png" | "webp") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unnamed")
            .to_string();
        let img = ImageReader::open(&path)
            .unwrap_or_else(|e| panic!("open {}: {}", path.display(), e))
            .with_guessed_format()
            .unwrap()
            .decode()
            .unwrap_or_else(|e| panic!("decode {}: {}", path.display(), e))
            .to_rgba8();
        entries.push((name, img));
    }

    // Sort by descending height for a better shelf packing.
    entries.sort_by(|a, b| b.1.height().cmp(&a.1.height()));

    // Shelf packing.
    let mut atlas = RgbaImage::from_pixel(ATLAS_W, 1, image::Rgba([0, 0, 0, 0]));
    let mut shelf_x: u32 = 0;
    let mut shelf_y: u32 = 0;
    let mut shelf_h: u32 = 0;
    let mut atlas_h: u32 = 0;

    let mut sprites: Vec<(String, u32, u32, u32, u32)> = Vec::new();

    for (name, img) in &entries {
        let (w, h) = img.dimensions();
        let pw = w + PADDING * 2;
        let ph = h + PADDING * 2;
        if pw > ATLAS_W {
            panic!("sprite '{}' too wide ({}) for atlas width {}", name, w, ATLAS_W);
        }
        if shelf_x + pw > ATLAS_W {
            // New shelf.
            shelf_y += shelf_h;
            shelf_x = 0;
            shelf_h = 0;
        }
        if shelf_y + ph > atlas.height() {
            // Grow atlas.
            let new_h = (shelf_y + ph).next_power_of_two().max(64);
            let mut bigger = RgbaImage::from_pixel(ATLAS_W, new_h, image::Rgba([0, 0, 0, 0]));
            bigger.copy_from(&atlas, 0, 0).unwrap();
            atlas = bigger;
        }
        let dx = shelf_x + PADDING;
        let dy = shelf_y + PADDING;
        for (sx, sy, px) in img.view(0, 0, w, h).pixels() {
            atlas.put_pixel(dx + sx, dy + sy, px);
        }
        sprites.push((name.clone(), dx, dy, w, h));
        shelf_x += pw;
        shelf_h = shelf_h.max(ph);
        atlas_h = atlas_h.max(shelf_y + shelf_h);
    }

    // Trim height to a power of two (or close to it) for nicety.
    let final_h = atlas_h.next_power_of_two().max(64);
    let mut final_img = RgbaImage::from_pixel(ATLAS_W, final_h, image::Rgba([0, 0, 0, 0]));
    for y in 0..atlas_h {
        for x in 0..ATLAS_W {
            final_img.put_pixel(x, y, *atlas.get_pixel(x, y));
        }
    }

    let png_path = out_dir.join("atlas.png");
    final_img
        .save_with_format(&png_path, image::ImageFormat::Png)
        .expect("save atlas.png");

    // Emit Rust source with sprite metadata.
    let mut rs = String::new();
    rs.push_str("// @generated by build.rs\n");
    rs.push_str(&format!("pub const ATLAS_W: u32 = {};\n", ATLAS_W));
    rs.push_str(&format!("pub const ATLAS_H: u32 = {};\n", final_h));
    rs.push_str("pub const ATLAS_PNG: &[u8] = include_bytes!(\"atlas.png\");\n");
    rs.push_str("\n");
    rs.push_str("pub struct SpriteRect {\n");
    rs.push_str("    pub name: &'static str,\n");
    rs.push_str("    pub x: u32, pub y: u32, pub w: u32, pub h: u32,\n");
    rs.push_str("}\n\n");
    rs.push_str("pub const SPRITES: &[SpriteRect] = &[\n");
    for (name, x, y, w, h) in &sprites {
        rs.push_str(&format!(
            "    SpriteRect {{ name: {:?}, x: {}, y: {}, w: {}, h: {} }},\n",
            name, x, y, w, h
        ));
    }
    rs.push_str("];\n");

    let rs_path = out_dir.join("atlas_data.rs");
    fs::write(&rs_path, rs).expect("write atlas_data.rs");

    let _ = (out_dir, Path::new("."));
}
